In [2]:
#Learning how to use numpy
import numpy as np

In [3]:
#Creating a numpy array of rank 1
arr1 = np.array([1, 2, 3])
print(arr1)

[1 2 3]


In [5]:
#Creating a numpy array of rank 2
arr2 = np.array([[1,2,3],
                [4,5,6]])
print(arr2)

[[1 2 3]
 [4 5 6]]


In [6]:
#Creating a numpy array from a tuple
arr3 = np.array((1,2,3))
print(arr3)

[1 2 3]


In [11]:
arr4 = np.array([[-1, 2, 0, 4],
                [4, -0.5, 6, 0],
                [2.6, 0, 7, 8],
                [3, -7, 4, 2.0]])

#Printing a range of array with the use of slicing method
arr5 = arr4[:2, ::2]
print("First two rows and the alternate columns(i.e. 0 & 2):\n", arr5)

First two rows and the alternate columns(i.e. 0 & 2):
 [[-1.  0.]
 [ 4.  6.]]


In [15]:
arr5 = arr4[[1,1,0,3],
            [3,2,1,0]]
print("\n Elements at indices (1, 3), (1, 2), (0, 1), (3, 0): \n", arr5)


 Elements at indices (1, 3), (1, 2), (0, 1), (3, 0): 
 [0. 6. 2. 3.]


In [18]:
# Now we'll play along with some array operations using numpy
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6], [7, 8]])

In [21]:
#Adding 1 to every element of x 
print(x + 1)

#Subtracting 2 from every element of y
print(y - 2)

[[2 3]
 [4 5]]
[[3 4]
 [5 6]]


In [24]:
# Unary operations: sum of all elements of an array
print(x.sum())

#Binary operations: sum of 2 arrays
print(x + y)

10
[[ 6  8]
 [10 12]]


In [28]:
#Constructing data type objects using numpy

#Integer data type
f = np.array([1, 2])
print(f.dtype)

#Float data type
g = np.array([1.0, 2.0])
print(g.dtype)

#Forced data type
h = np.array([1, 2], dtype = np.int64)
print(h.dtype)

int32
float64
int64


In [37]:
#Performing mathematical operations using numpy
i = np.array([[4, 7], [2, 6]], dtype = np.float64)
j = np.array([[3, 6], [2, 8]], dtype = np.float64)


#Sum of two arrays
sum  = np.add(i, j)
print(sum)

#Sum of all elements in an array
sum1 = np.sum(i)
print(sum1)

#Square root of elements of an array
Sqrt = np.sqrt(i)
print(Sqrt)

#Tranpose of elements of an array
print(i)
trans_i = i.T
print(trans_i)

[[ 7. 13.]
 [ 4. 14.]]
19.0
[[2.         2.64575131]
 [1.41421356 2.44948974]]
[[4. 7.]
 [2. 6.]]
[[4. 2.]
 [7. 6.]]
