In [2]:
#Learning how to use numpy
import numpy as np

In [3]:
#Creating a numpy array of rank 1
arr1 = np.array([1, 2, 3])
print(arr1)

[1 2 3]


In [5]:
#Creating a numpy array of rank 2
arr2 = np.array([[1,2,3],
                [4,5,6]])
print(arr2)

[[1 2 3]
 [4 5 6]]


In [6]:
#Creating a numpy array from a tuple
arr3 = np.array((1,2,3))
print(arr3)

[1 2 3]


In [11]:
arr4 = np.array([[-1, 2, 0, 4],
                [4, -0.5, 6, 0],
                [2.6, 0, 7, 8],
                [3, -7, 4, 2.0]])

#Printing a range of array with the use of slicing method
arr5 = arr4[:2, ::2]
print("First two rows and the alternate columns(i.e. 0 & 2):\n", arr5)

First two rows and the alternate columns(i.e. 0 & 2):
 [[-1.  0.]
 [ 4.  6.]]


In [15]:
arr5 = arr4[[1,1,0,3],
            [3,2,1,0]]
print("\n Elements at indices (1, 3), (1, 2), (0, 1), (3, 0): \n", arr5)


 Elements at indices (1, 3), (1, 2), (0, 1), (3, 0): 
 [0. 6. 2. 3.]


In [ ]:
# Now we'll play along with some array operations using numpy